name: rpc_mongo_mapper
version: 0.1.2
description: >
  rpc_mongo_mapper is a package that allow you to easily provide CRUD operation to a class
  with rpc and store its representation inside mongodb
author: ProfileRH, PLATEL Kevin <platel.kevin@gmail.com>
homepage: https://github.com/ProfileRH/rpc_mongo_mapper
environment:
  sdk: ">=1.12.0 <2.0.0"
dependencies:
  rpc:
    git:
      url: https://github.com/platelk/rpc.git
  mongo_dart: "^0.2.4"
  amqp_rpc_binder: "^0.1.0"
  logging: "0.11.1+1"
dependency_overrides:
  logging: "0.11.1+1"